#!/bin/bash
if [ -z $STAGING_PATH ]; then
  echo "Staging directory is not set, exiting..."
  exit
fi
cd $STAGING_PATH
DATESTAMP=$(date "+%F %T")
git add .
git commit -m "Website change on $DATESTAMP"
git push
